---
format_version: 3
pipelines:
  "node-build":
    group: as-code
    materials:
      gh:
        git: https://github.com/marques-work/sample-node.git
    environment_variables:
      FOO: bar
      BAZ: quu
    stages:
      - first:
          tasks:
            - exec:
                command: which
                arguments:
                  - date
      - second:
          tasks:
            - exec:
                command: echo
                arguments:
                  - FOO is $FOO

  balderdash:
    group: as-code
    materials:
      gh:
        git: https://github.com/marques-work/sample-node.git
    stages:
      - first:
          tasks:
            - exec:
                command: echo
                arguments:
                  - poppycock
      - second:
          tasks:
            - exec:
                command: say
                arguments:
                  - oh
                  - snap
