format_version: 3
pipelines:
  config42:
    group: first
    template: the42
    label_template: ${COUNT}
    lock_behavior: none
    materials:
      git:
        git: https://github.com/marques-work/sample-node
        shallow_clone: false
        auto_update: true
        branch: template-test
