---
format_version: 3
pipelines:
  node-build:
    group: as-code
    materials:
      git: https://github.com/marques-work/sample-node.git
    environment_variables:
      FOO: bar
    stages:
      - first:
          tasks:
            - exec:
                command: which
                arguments:
                  - date
      - second:
          tasks:
            - exec:
                command: echo
                arguments:
                  - FOO is $FOO
