---
format_version: 5
environments:
  uno:
    pipelines:
      - node-build
      - lolz
  dos:
    pipelines:
      - balderdash
      - roflmao
pipelines:
  "node-build":
    group: as-code
    materials:
      gh:
        git: https://github.com/marques-work/sample-node.git
    environment_variables:
      FOO: bar
      BAZ: quu
    stages:
      - first:
          tasks:
            - exec:
                command: which
                arguments:
                  - date
      - second:
          tasks:
            - exec:
                command: echo
                arguments:
                  - FOO is $FOO

  balderdash:
    group: as-code
    materials:
      gh:
        git: https://github.com/marques-work/sample-node.git
    stages:
      - first:
          tasks:
            - exec:
                command: echo
                arguments:
                  - poppycock
      - second:
          tasks:
            - exec:
                command: say
                arguments:
                  - oh
                  - snap
  lolz:
    group: ass-code
    materials:
      gh:
        git: https://github.com/marques-work/sample-node.git
    stages:
      - one:
          tasks:
            - exec:
                command: id
      - two:
          tasks:
            - exec:
                command: w
      - three:
          tasks:
            - exec:
                command: echo
                arguments:
                  - sine yo pitty on the runny kine

  roflmao:
    group: ass-code
    materials:
      gh:
        git: https://github.com/marques-work/sample-node.git
    stages:
      - first:
          tasks:
            - exec:
                command: echo
                arguments:
                  - sepatown
