---
spring:
  #                  __                   __
  # _____     ____ _/  |_  __ __ _____  _/  |_  ____ _______
  # \__  \  _/ ___\\   __\|  |  \\__  \ \   __\/  _ \\_  __ \
  #  / __ \_\  \___ |  |  |  |  / / __ \_|  | (  <_> )|  | \/
  # (____  / \___  >|__|  |____/ (____  /|__|  \____/ |__|
  #      \/      \/                   \/
management:
  endpoints:
    web:
      exposure:
        include: info,health
  info:
    env:
      enabled: true

info:
  app:
    version: 2.0
